### ISSUE TITLE
PV Output team

### ISSUE THREAD

**Issue by mistaoh** [bohdan-s/SunGather#11]
The default team joining does not work if you have to few outputs. I got this response until i changed to join_team: False 
`2022-01-18 09:28:17 ERROR PVOutput: Team update Failed; 400 Message; b'Bad request 400: Your system must have at least 5 outputs to join a team'`

**Comment by bohdan-s** [comment]
Resolved in 0.2.9+, will not try and join unless 5+ outputs :)
