### ISSUE TITLE
Register Numbers in Webview

### ISSUE THREAD

**Issue by benni336** [bohdan-s/SunGather#15]
thanks for your work :)
would it be easy to show the register number alongside the name in the web view? it would make debugging a lot faster for me

_Originally posted by @chainsawbike in https://github.com/bohdan-s/SunGather/issues/1#issuecomment-1018170828_

**Comment by bohdan-s** [comment]
I should have a new build up next week. Re-writing a bunch of code. I've kept adding new things now need to consolidate and clean it up.

**Comment by benni336** [comment]
This would be a great future (maybe together with log level binding)?

Because I currently have a problem. I added register, but they don't seem to show up in consol and webview. :(
... Yes I have adapted scanning. Maybe this feature could help me finding the problem

**Comment by bohdan-s** [comment]
Yup, wait for the new build. Refactoring code to allow it to do more things :) also adding a file export to log to file for those who want it.

**Comment by benni336** [comment]
> I should have a new build up next week. Re-writing a bunch of code. I've kept adding new things now need to consolidate and clean it up.

@bohdan-s . I don't want to put any pressure on you. But could you think about just pushing this into an own branch directly? Like a feature branch or a nightly build?

It would make the work for me a bit simpler as I can directly see your changes (they don't need to work or be good). It's a nightly and I could base my development on your last changes as we are in different time zones and seem to have similar ideas and I am currently heavily working on code.

**Comment by bohdan-s** [comment]
Sure,
I'm just working on a new build environment to support Raspberry Pi and home assistant then I'll set up a nightly.

**Comment by benni336** [comment]
Why is raspberry Pi currently not supported? It's python? Did I miss something?

**Comment by bohdan-s** [comment]
v0.3.0 pushed, has addresses listed in console and web-server output now, as well as the unit type. This should help :)
