### ISSUE TITLE
Dependancy created on the config.yaml 'logger'

### ISSUE THREAD

**Issue by MarkGardiner** [bohdan-s/SunGather#19]
Hey,

Just been following the master branch and noticed that there is no longer a check on the existance of the logger parameter in the config.yaml file:

https://github.com/bohdan-s/SunGather/blob/1b54ae3a708e10478fea6f1270153df6c093bfa5/SunGather/sungather.py#L438

**Comment by bohdan-s** [comment]
Aahhh thank you, I missed one, moving them all to a central config block. 
I’ll for that for next release.

**Comment by bohdan-s** [comment]
In fact I missed all the defaults there, i'll push 0.3.1 shortly.

**Comment by bohdan-s** [comment]
fixed in 0.3.1 :)
