### ISSUE TITLE
Home Assistant Addon (HACS)

### ISSUE THREAD

**Issue by ratava** [bohdan-s/SunGather#29]
Dev issue for  the new HA Addon for Sungather. 

Current state is working SunGather under Terminal SSH Docker Session. Working Addon install interface. To Do: Complete Dockerfile to install prerequistes for python.

**Comment by benni336** [comment]
Hi, can you point out what do you mean by "HA Addon"?

**Comment by bohdan-s** [comment]
HA = Home Assistant 
At the moment it does MQTT and auto discovery. But I would like to fully integrate it so it can be run as an add on instead of standalone script / docker

**Comment by bohdan-s** [comment]
Sorry, this is my next priority. 
Have to re-write some code to allow it to run in HA/HACS

**Comment by highground88** [comment]
How is this coming along? Waiting to try it 😁 Thanks

**Comment by andres-canello** [comment]
I'll be happy to test and buy you beer as well :)

**Comment by bohdan-s** [comment]
This has been published as a Hass.io Addon, see  https://github.com/bohdan-s/hassio-repository
