### ISSUE TITLE
SG5.0RS support

### ISSUE THREAD

**Issue by puijken** [bohdan-s/SunGather#32]
Hello,

Is this guy supported? I hoped it would be very similair to SH5.0RS but unfortunately none of the settings seem to work. Tried various combination in the config file.

Running the docker container if this would be any different.

If you can tell me which config is most likely to work I can post some logging output from the container.
Thanks!

**Comment by benni336** [comment]
If you have a WiNet-S Dongle, then http mode should work. (See my sg10rt issue)

**Comment by puijken** [comment]
Thanks for the information - i'll close this and follow up in your issue as I'm having exactly the same problem.
