### ISSUE TITLE
Inverter Power State incorrectly OFF

### ISSUE THREAD

**Issue by rark-ha** [bohdan-s/SunGather#43]
After checking the terminal entries and then logging into the web page, I was logged out of the web page (presumably SunGather was doing it's next scrape).

The reading for run_state started showing OFF when it was in fact ON (confirmed via the web page). I restarted the container to get it to show ON again. Capture of the bug below.

![image](https://user-images.githubusercontent.com/62318984/162886459-c547e32c-b969-47e5-a6f2-a7c00c09f9c3.png)

**Comment by puijken** [comment]
I can confirm this issue .. I'm using this to parameter in my logic in NodeRED but this morning my values were not reporting -> seemed run_state was still OFF but the inverter was running and producing energy.

**Comment by danielHin** [comment]
Hey @rark-ha can you still reproduce this with the latest version of SunGather? there was some work done around this registers, maybe this is fixed now

**Comment by rark-ha** [comment]
No I can't reproduce this issue now

**Comment by puijken** [comment]
Unfortunately the issue still seems to exist ... please find below an output from my NodeRED where you can clearly see the inverter is running but it still reports "run_state" = OFF

Inverter = SG5.0RS

![image](https://user-images.githubusercontent.com/77811176/182021025-385b0e14-d64b-4a54-8d52-f71552c61c8a.png)
