### ISSUE TITLE
Mapping for running_state

### ISSUE THREAD

**Issue by michbeck100** [bohdan-s/SunGather#53]
I started using SunGather and I'm thinking to move from modbus4mqtt. Unfortunately it seems that SunGather doesn't support a mapping for `running_state`. 
According to the sungrow documentation this is the mapping:
![image](https://user-images.githubusercontent.com/5385572/171630356-c8258767-0afb-4888-bea5-83ce50f45b57.png)
So `running_state` actually contains 8 values.

How can I achieve such a mapping?

**Comment by danielHin** [comment]
Hi, the merge introduced a bug. 

`Traceback (most recent call last):
  File "sungather.py", line 584, in <module>
    main()
  File "sungather.py", line 552, in main
    export.publish(inverter)
  File "/src/github/SunGather/SunGather/exports/console.py", line 26, in publish
    print("| {:<7} | {:<35} | {:<20} |".format(str(inverter.getRegisterAddress(register)), str(register), str(value) + " " + str(inverter.getRegisterUnit(register))))
  File "sungather.py", line 265, in getRegisterAddress
    return register['address']
KeyError: 'address'
`

**Comment by michbeck100** [comment]
No it happens when reading run_state, which is a custom register without address. It used to have a "virtual" address, but commit bc8493fee93e3c3488930ccc0660a5deef1a455d changed this. This is not because of my changes.

**Comment by michbeck100** [comment]
this fixes it again: https://github.com/bohdan-s/SunGather/pull/57

**Comment by danielHin** [comment]
thy for fixing. 

@michbeck100 @bohdan-s 
another issue I've just saw.  The newly introduced 'import_from_grid' register in the registers file clashes with the custom 'import_from_grid' register and overwrites the value. 

Maybe we rename the running state registers by prefix them with state_ or running_state_ ? 

Alternatively we could rename import_from_grid and export_to_grid to custom_*.

 But its more obvious at lest to me to rename the new running state registers to make it more clear

**Comment by danielHin** [comment]
proposed renaming in #59

**Comment by michbeck100** [comment]
I think this can be closed now
